### PR TITLE
Tons of features added, some fixes, a few things removed

### PR DESCRIPTION
**Pull request by gotmachine**
- Hirearchy : reworked the general UI options
- Hierarchy : reworked mouse hover selection, now require holding ALT, added UI/object selection capacities
- Hierarchy : huge performance improvements (doesn't re-parse anymore the whole scene hierarchy every update)
- Hierarchy : ability to find/show disabled objects
- Hierarchy : ability to browse/search the whole resource database (prefabs, internal unity objects...), by object name or by component type (a bit laggy but does the job)
- Hierarchy : now show objects in the right order
- Hierarchy : removed sorting feature and ability to dump the hierarchy to a text file (could be re-added if necessary but that's a bit useless and I'm lazy)
- The wireframe viewer is now only added to the selected object and not whole hierarchy (was causing severe perf issue)
- Added wireframe visualization for RectTransforms
- Fixed toolbar button not showing with stock toolbar (was working only with blizzy)
- Inspector : now only show details for only 1 component at a time (fix lag with large/many component), better usability.
- Inspector : now show the gameobject fields/properties (and not only the components)
- Inspector : allow to enable/disable gameobjects
- Inspector : various UI tweaks alignment, colors, handling of long values, fix height flickering...
- Inspector : option to show non public / static members
- Added a "value editor", allow setting fields/properties for primitive types and some common Unity/KSP primitives (Color, Vector, Quaternion, etc...)

image

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
You are saying that the toolbarController was not working properly?  I don't understand, it is irrelevent as to what it uses.  What wasn't working?
I guess you didn't bother to read your emails, I closed this PR.  I'll reopen it, but would like to understand what you've done, you made a lot of changes which I have to review

Edit:  I just tested the current version, and the toolbar button works well with both the stock and the blizzy toolbar.  So now I am extremely puzzled and concerned about the rest of the changes.  Please respond

**Comment by gotmachine** [comment]
EDITED : after more testing, the toolbar issue is indeed a ToolbarController bug. Steps to reproduce :
- Uninstall ToolbarController, Blizzy and KOI (make sure you delete everything including plugindata)
- Reinstall KOI + ToolbarController (don't install blizzy)
- Launch the game : the KOI toolbar button won't show up. It is registered in the ToolbarController dialog, but it isn't added to stock toolbar.
- Close the game, re-launch : now the KOI toolbar button will show up.

The fix I did doesn't actually fix anything. I just changed `ApplicationLauncher.AppScenes.ALWAYS` to declaring each scene individually, but I was mislead by the fact that it is fixed just by relaunching the game.

My guess is that a just-installed ToolbarController is (re)initialized too late, on the first space center scene load, after the KOI KSPAddon was started in the main menu. There aren't many mods using a main menu toolbar button, so the issue has probably gone under the radar.

As for the other changes, what are your concerns ?

Yes I basically rewrote the entire hierarchy class, it was horribly laggy and inefficient, plus it had annoying limitations/issues like the inability to show/find disabled gameobjects and the fact that the hierarchy was in reversed order. And I also did major changes to the inspector to give it all the new abilities I mentioned.

**Comment by linuxgurugamer** [comment]
My concern was the comment about the button without an explanation.  Without doing extensive work, I think your guess is probably right on the money.  The only change I suggest would be to instead of adding all the scenes, you can use ALLGAMESCENES.
I'll try to review the rest over the next few days

**Comment by linuxgurugamer** [comment]
Just an FYI, your comment above:
My guess is that a just-installed ToolbarController is (re)initialized too late, on the first space center scene load, after the KOI KSPAddon was started in the main menu. There aren't many mods using a main menu toolbar button, so the issue has probably gone under the radar.
I am only aware of maybe two or three mods which use buttons on the main menu.  TBC does not initialize until the main menu, and in fact, the instructions for using are that the RegisterToolbar method should be called at the mian menu due to initialization sequencing.
I don't know why you would want this to be started on the main menu, though

**Pull request merged**
